name: Build

on:
 workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: self-hosted
   
    steps:
    - uses: actions/checkout@v4

  windows:
    name: Windows Build
    runs-on: windows-latest
    #needs: [cypress]

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Download Wiki.js for Windows
      run: |
        Invoke-WebRequest -Uri "https://github.com/requarks/wiki/releases/download/v2.5.305/wiki-js-windows.tar.gz" -OutFile "$env:GITHUB_WORKSPACE\wiki-js-windows.tar.gz"

    - name: Extract Wiki.js
      run: |
        mkdir -p win
        tar -xzf $env:GITHUB_WORKSPACE\wiki-js-windows.tar.gz -C $env:GITHUB_WORKSPACE\win
