name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: self-hosted
       
    steps:
    # - name: Setup Node.js environment
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 20.x

    - name: Clean Workspace
      run: |
        if (Test-Path $env:GITHUB_WORKSPACE\*) {
          Remove-Item $env:GITHUB_WORKSPACE\* -Force -Recurse
        }

    - name: Download Wiki.js for Windows
      run: |
        Invoke-WebRequest -Uri "https://github.com/Requarks/wiki/releases/latest/download/wiki-js-windows.tar.gz" -OutFile "wiki-js-windows.tar.gz"

    - name: Extract Wiki.js
      run: |
         tar -xzf wiki-js-windows.tar.gz -C win

    - name: Clean Downloaded File
      run: del wiki-js-windows.tar.gz

    # Rename config.sample.yml to config.yml
    - name: Rename config.sample.yml to config.yml
      run: |
        Rename-Item -Path "$env:GITHUB_WORKSPACE/config.sample.yml" -NewName "config.yml"
