name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: self-hosted
       
    steps:
    # - name: Setup Node.js environment
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 20.x

    - name: Clean Workspace
      run: |
        if (Test-Path $env:GITHUB_WORKSPACE\*) {
          Remove-Item $env:GITHUB_WORKSPACE\* -Force -Recurse
        }

    - name: Download Wiki.js for Windows
      run: |
        Invoke-WebRequest -Uri "https://github.com/Requarks/wiki/releases/latest/download/wiki-js-windows.tar.gz" -OutFile "wiki-js-windows.tar.gz"

    - name: Extract Wiki.js
      run: |
         tar -xzf wiki-js-windows.tar.gz -C $env:GITHUB_WORKSPACE

    - name: Clean Downloaded File
      run: del wiki-js-windows.tar.gz

    # Rename config.sample.yml to config.yml
    - name: Rename config.sample.yml to config.yml
      run: |
        Rename-Item -Path "$env:GITHUB_WORKSPACE/config.sample.yml" -NewName "config.yml"


    - name: Edit config.yml with Secrets
      run: |
        $configPath = "$env:GITHUB_WORKSPACE/config.yml"
        if (Test-Path $configPath) {
          # Read the config.yml file
          $config = Get-Content $configPath -Raw

          # Define the start and end comments
          $startComment = '# PostgreSQL / MySQL / MariaDB / MS SQL Server only:'
          $endComment = '# Optional - PostgreSQL / MySQL / MariaDB only:'

          # Find the section between start and end comments
          $startIndex = $config.IndexOf($startComment)
          $endIndex = $config.IndexOf($endComment)

          if ($startIndex -ge 0 -and $endIndex -ge 0 -and $startIndex -lt $endIndex) {
            # Extract the section between start and end comment
            $sectionToEdit = $config.Substring($startIndex, $endIndex - $startIndex)

            # Replace the database section with secrets within this section
            $sectionToEdit = $sectionToEdit -replace 'host:.*', "host: ${{ secrets.DB_HOST }}"
            $sectionToEdit = $sectionToEdit -replace 'port:.*', "port: ${{ secrets.DB_PORT }}"
            $sectionToEdit = $sectionToEdit -replace 'user:.*', "user: ${{ secrets.DB_USER }}"
            $sectionToEdit = $sectionToEdit -replace 'pass:.*', "pass: ${{ secrets.DB_PASS }}"
            $sectionToEdit = $sectionToEdit -replace 'db:.*', "db: ${{ secrets.DB_NAME }}"
            $sectionToEdit = $sectionToEdit -replace 'ssl:.*', "ssl: ${{ secrets.DB_SSL }}"

            # Replace the original section in the config file with the modified section
            $config = $config.Substring(0, $startIndex) + $sectionToEdit + $config.Substring($endIndex)

            # Write the changes back to config.yml
            Set-Content -Path $configPath -Value $config
          } else {
            Write-Error "Start or end comment not found or invalid indices!"
          }
        } else {
          Write-Error "config.yml not found!"
        }
