name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: self-hosted
       
    steps:
    # - name: Setup Node.js environment
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 20.x

    - name: Clean Workspace
      run: |
        if (Test-Path $env:GITHUB_WORKSPACE\*) {
          Remove-Item $env:GITHUB_WORKSPACE\* -Force -Recurse
        }

    - name: Download Wiki.js for Windows
      run: |
        Invoke-WebRequest -Uri "https://github.com/Requarks/wiki/releases/latest/download/wiki-js-windows.tar.gz" -OutFile "wiki-js-windows.tar.gz"

    - name: Extract Wiki.js
      run: |
         tar -xzf wiki-js-windows.tar.gz -C $env:GITHUB_WORKSPACE

    - name: Clean Downloaded File
      run: del wiki-js-windows.tar.gz

    # Rename config.sample.yml to config.yml
    - name: Rename config.sample.yml to config.yml
      run: |
        Rename-Item -Path "$env:GITHUB_WORKSPACE/config.sample.yml" -NewName "config.yml"

    # Edit config.yml with Secrets
    - name: Edit config.yml with Secrets
      run: |
        $configPath = "$env:GITHUB_WORKSPACE/config.yml"
        if (Test-Path $configPath) {
          # Read the config.yml file
          $config = Get-Content $configPath -Raw

          # Replace the values with secrets
          $config = $config -replace 'host:.*', "host: ${{ secrets.DB_HOST }}"
          $config = $config -replace 'port:.*', "port: ${{ secrets.DB_PORT }}"
          $config = $config -replace 'user:.*', "user: ${{ secrets.DB_USER }}"
          $config = $config -replace 'pass:.*', "pass: ${{ secrets.DB_PASS }}"
          $config = $config -replace 'db:.*', "db: ${{ secrets.DB_NAME }}"
          $config = $config -replace 'ssl:.*', "ssl: ${{ secrets.DB_SSL }}"

          # Write the changes back to config.yml
          Set-Content -Path $configPath -Value $config
        } else {
          Write-Error "config.yml not found!"
        }
